### ISSUE TITLE
Make it easier to fill the preference page

### ISSUE THREAD

**Issue by bkolb** [Workday/mps-code-reviewer#12]
I had to ask @szabta89 in order to understand what to fill in the preference page. It would be nice if I could just copy the the repository URL and the page would figure out on its own

**Comment by sergej-koscejev** [comment]
I agree, while I have figured out most fields (I think), I have no idea what to fill in as "API Version" for example. A "Test" button would be nice.

**Comment by ty1824** [comment]
I believe this should be easier now, I've replaced the four various URL components w/ the repository's full user-accessible URL. It extracts the relevant info from that URL.

Haven't created a "Test" button yet, though!
